import React, { useMemo } from 'react';
import { View, Text, StyleSheet, ScrollView, Pressable, Alert } from 'react-native';
import { useLocalSearchParams, useRouter, Stack } from 'expo-router';
import { Navigation, Clock, Gauge, Calendar, Trash2, MapPin, Share2, MessageCircle, Mail, FileText } from 'lucide-react-native';
import { useTrips } from '@/providers/TripProvider';
import { useI18n } from '@/providers/I18nProvider';
import { Colors } from '@/constants/colors';
import { formatDistance, formatDuration, formatDate, formatTime, formatDurationLong } from '@/utils/format';
import { escapeHtml, shareByEmail, shareBySms, sharePdfFile, shareText, showShareError } from '@/utils/sharing';

export default function TripDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const { trips, deleteTrip, getProjectName, getVehicleName, settings } = useTrips();
  const { t } = useI18n();

  const trip = useMemo(() => trips.find((tr) => tr.id === id), [trips, id]);

  const handleDelete = () => {
    Alert.alert(t.deleteTrip, t.deleteTripMsg, [
      { text: t.cancel, style: 'cancel' },
      {
        text: t.delete,
        style: 'destructive',
        onPress: () => {
          if (trip) {
            deleteTrip(trip.id);
            router.back();
          }
        },
      },
    ]);
  };

  const purposeLabel = useMemo(() => {
    if (!trip) return '';
    const key = trip.purpose as keyof typeof t;
    return t[key] ?? trip.purpose.charAt(0).toUpperCase() + trip.purpose.slice(1);
  }, [trip, t]);

  if (!trip) {
    return (
      <View style={styles.container}>
        <Stack.Screen options={{ title: t.trip }} />
        <View style={styles.emptyState}>
          <Text style={styles.emptyText}>{t.tripNotFound}</Text>
        </View>
      </View>
    );
  }

  const purposeColor = Colors.purposes[trip.purpose] ?? Colors.textSecondary;
  const projectName = getProjectName(trip.projectId);
  const vehicleName = getVehicleName(trip.vehicleId);
  const avgSpeedMph = trip.duration > 0 ? trip.distance / (trip.duration / 3600) : 0;
  const avgSpeed = settings.distanceUnit === 'km'
    ? (avgSpeedMph * 1.60934).toFixed(1)
    : avgSpeedMph.toFixed(1);
  const distanceUnit = settings.distanceUnit === 'km' ? 'km' : 'mi';
  const distance = `${formatDistance(trip.distance, settings.rounding, settings.distanceUnit)} ${distanceUnit}`;
  const subject = `TapMiles trip – ${formatDate(trip.startTime)}`;
  const tripMessage = [
    subject,
    `Distance: ${distance}`,
    `Time: ${formatTime(trip.startTime)} – ${formatTime(trip.endTime)}`,
    `Duration: ${formatDurationLong(trip.duration)}`,
    `Purpose: ${purposeLabel}`,
    `Vehicle: ${vehicleName ?? 'Not selected'}`,
    `Project: ${projectName ?? 'None'}`,
    trip.notes ? `Notes: ${trip.notes}` : null,
  ].filter(Boolean).join('\n');

  const handleShare = async () => {
    try {
      await shareText(subject, tripMessage);
    } catch (error) {
      showShareError(error);
    }
  };

  const handleSms = async () => {
    try {
      await shareBySms(tripMessage);
    } catch (error) {
      showShareError(error);
    }
  };

  const handleEmail = async () => {
    try {
      await shareByEmail(subject, tripMessage);
    } catch (error) {
      showShareError(error);
    }
  };

  const handlePdf = async () => {
    const detailRows = [
      ['Date', formatDate(trip.startTime)],
      ['Time', `${formatTime(trip.startTime)} – ${formatTime(trip.endTime)}`],
      ['Distance', distance],
      ['Duration', formatDurationLong(trip.duration)],
      ['Purpose', purposeLabel],
      ['Vehicle', vehicleName ?? 'Not selected'],
      ['Project', projectName ?? 'None'],
      ['GPS points', trip.routePoints.length],
      ['Notes', trip.notes || '—'],
    ].map(([label, value]) => `<tr><th>${escapeHtml(label)}</th><td>${escapeHtml(value)}</td></tr>`).join('');
    const html = `<!doctype html><html><head><meta charset="utf-8"><style>
      @page { margin: 42px; } body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; color: #17202a; }
      h1 { color: #00a978; margin-bottom: 4px; } .distance { font-size: 34px; font-weight: 800; margin: 12px 0 24px; }
      table { width: 100%; border-collapse: collapse; } th, td { border-bottom: 1px solid #d9e2ec; padding: 11px 8px; text-align: left; }
      th { width: 28%; color: #52606d; } .footer { margin-top: 28px; font-size: 10px; color: #7b8794; }
    </style></head><body><h1>TapMiles Trip Report</h1><p>${escapeHtml(formatDate(trip.startTime))}</p>
      <div class="distance">${escapeHtml(distance)}</div><table>${detailRows}</table>
      <p class="footer">Generated by TapMiles Mileage Tracker</p></body></html>`;
    try {
      await sharePdfFile(`TapMiles-trip-${new Date(trip.startTime).toISOString().slice(0, 10)}.pdf`, html, 'Share TapMiles trip PDF');
    } catch (error) {
      showShareError(error);
    }
  };

  return (
    <View style={styles.container}>
      <Stack.Screen
        options={{
          title: formatDate(trip.startTime),
          headerRight: () => (
            <View style={styles.headerActions}>
              <Pressable onPress={handleShare} hitSlop={8} accessibilityLabel="Share trip">
                <Share2 size={20} color={Colors.accent} />
              </Pressable>
              <Pressable onPress={handleDelete} hitSlop={8} accessibilityLabel="Delete trip">
                <Trash2 size={20} color={Colors.danger} />
              </Pressable>
            </View>
          ),
        }}
      />
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.heroCard}>
          <View
            style={[
              styles.purposeBadge,
              { backgroundColor: purposeColor + '20' },
            ]}
          >
            <Text style={[styles.purposeText, { color: purposeColor }]}>
              {purposeLabel}
            </Text>
          </View>
          <Text style={styles.heroDistance}>
            {formatDistance(trip.distance, settings.rounding, settings.distanceUnit)}
          </Text>
          <Text style={styles.heroUnit}>{settings.distanceUnit === 'km' ? t.kilometers : t.miles}</Text>
        </View>

        <View style={styles.statsGrid}>
          <View style={styles.statCard}>
            <Clock size={18} color={Colors.accent} />
            <Text style={styles.statValue}>{formatDuration(trip.duration)}</Text>
            <Text style={styles.statLabel}>{t.duration}</Text>
          </View>
          <View style={styles.statCard}>
            <Gauge size={18} color={Colors.accent} />
            <Text style={styles.statValue}>{avgSpeed}</Text>
            <Text style={styles.statLabel}>{settings.distanceUnit === 'km' ? t.avgKmh : t.avgMph}</Text>
          </View>
          <View style={styles.statCard}>
            <MapPin size={18} color={Colors.accent} />
            <Text style={styles.statValue}>{trip.routePoints.length}</Text>
            <Text style={styles.statLabel}>{t.gpsPoints}</Text>
          </View>
        </View>

        <View style={styles.detailsSection}>
          <View style={styles.detailRow}>
            <Calendar size={16} color={Colors.textSecondary} />
            <Text style={styles.detailLabel}>{t.date}</Text>
            <Text style={styles.detailValue}>
              {formatDate(trip.startTime)}
            </Text>
          </View>
          <View style={styles.divider} />
          <View style={styles.detailRow}>
            <Clock size={16} color={Colors.textSecondary} />
            <Text style={styles.detailLabel}>{t.time}</Text>
            <Text style={styles.detailValue}>
              {formatTime(trip.startTime)} – {formatTime(trip.endTime)}
            </Text>
          </View>

          {projectName && (
            <>
              <View style={styles.divider} />
              <View style={styles.detailRow}>
                <Navigation size={16} color={Colors.textSecondary} />
                <Text style={styles.detailLabel}>{t.project}</Text>
                <Text style={styles.detailValue}>{projectName}</Text>
              </View>
            </>
          )}

          {vehicleName && (
            <>
              <View style={styles.divider} />
              <View style={styles.detailRow}>
                <Navigation size={16} color={Colors.textSecondary} />
                <Text style={styles.detailLabel}>{t.vehicle}</Text>
                <Text style={styles.detailValue}>{vehicleName}</Text>
              </View>
            </>
          )}
        </View>

        {trip.notes.length > 0 && (
          <View style={styles.notesSection}>
            <Text style={styles.notesSectionLabel}>{t.notes}</Text>
            <Text style={styles.notesText}>{trip.notes}</Text>
          </View>
        )}

        <Text style={styles.shareTitle}>SHARE TRIP</Text>
        <View style={styles.shareGrid}>
          <Pressable style={({ pressed }) => [styles.shareButton, pressed && styles.buttonPressed]} onPress={handleSms}>
            <MessageCircle size={20} color={Colors.accent} />
            <Text style={styles.shareButtonText}>SMS</Text>
          </Pressable>
          <Pressable style={({ pressed }) => [styles.shareButton, pressed && styles.buttonPressed]} onPress={handleEmail}>
            <Mail size={20} color={Colors.accent} />
            <Text style={styles.shareButtonText}>Email</Text>
          </Pressable>
          <Pressable style={({ pressed }) => [styles.shareButton, pressed && styles.buttonPressed]} onPress={handlePdf}>
            <FileText size={20} color={Colors.accent} />
            <Text style={styles.shareButtonText}>PDF</Text>
          </Pressable>
          <Pressable style={({ pressed }) => [styles.shareButton, pressed && styles.buttonPressed]} onPress={handleShare}>
            <Share2 size={20} color={Colors.accent} />
            <Text style={styles.shareButtonText}>More</Text>
          </Pressable>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: Colors.textSecondary,
  },
  heroCard: {
    backgroundColor: Colors.card,
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    marginBottom: 16,
    gap: 4,
  },
  purposeBadge: {
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 10,
    marginBottom: 12,
  },
  purposeText: {
    fontSize: 13,
    fontWeight: '600' as const,
  },
  heroDistance: {
    fontSize: 56,
    fontWeight: '800' as const,
    color: Colors.text,
    lineHeight: 60,
  },
  heroUnit: {
    fontSize: 16,
    color: Colors.textSecondary,
    fontWeight: '500' as const,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: Colors.card,
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    gap: 6,
  },
  statValue: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: Colors.text,
  },
  statLabel: {
    fontSize: 11,
    color: Colors.textMuted,
    fontWeight: '500' as const,
  },
  detailsSection: {
    backgroundColor: Colors.card,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 6,
  },
  detailLabel: {
    fontSize: 14,
    color: Colors.textSecondary,
    flex: 1,
  },
  detailValue: {
    fontSize: 14,
    color: Colors.text,
    fontWeight: '600' as const,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.border,
    marginVertical: 4,
  },
  notesSection: {
    backgroundColor: Colors.card,
    borderRadius: 14,
    padding: 16,
  },
  notesSectionLabel: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: Colors.textMuted,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  notesText: {
    fontSize: 15,
    color: Colors.text,
    lineHeight: 22,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
  },
  shareTitle: {
    marginTop: 20,
    marginBottom: 10,
    fontSize: 12,
    fontWeight: '600' as const,
    color: Colors.textMuted,
    letterSpacing: 0.8,
  },
  shareGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  shareButton: {
    flex: 1,
    minHeight: 68,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Colors.accentDim,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.accent + '35',
  },
  shareButtonText: {
    color: Colors.accent,
    fontSize: 12,
    fontWeight: '600' as const,
  },
  buttonPressed: {
    opacity: 0.65,
  },
});
